#!/bin/ksh
if [[ -z "$1" ]]; then
  echo "Please provide commit message..."
else
  echo "Commit message: " $1
  coffee -o lib -c src
  coffee -o test -c srcTest
  broken=`vows | grep broken`
  if [[ $broken = *broken* ]]; then
    echo "Cannot push to github. The following tests failed:"
    vows
    exit 2
  else
    # push to github only when all tests pass
    git add .
    echo "git status before deploy"
    git status
    git commit -m $1
    git push
    echo "git status after deploy"
    git status
  fi
fi